services:
  db:
    image: postgres:15-alpine
    container_name: kajas-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kajas_db
    ports:
      - "5480:5432"
    volumes:
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: kajas-backend
    command: npm run dev
    ports:
      - "3080:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: kajas_db
      JWT_SECRET: supersecretkey_cambiame_en_produccion
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
      - kajas_uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: kajas-frontend
    ports:
      - "5180:5173"
    environment:
      - VITE_API_URL=http://localhost:3080/api
    depends_on:
      - backend

    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
  kajas_uploads:
